# Generated by Django 5.0.7 on 2024-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabit',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='date_finish',
        ),
        migrations.AlterField(
            model_name='userhabit',
            name='date_of_assign',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
