# Generated by Django 5.0.7 on 2024-07-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_remove_userhabit_current_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='days_to_achieve',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='times_per_day',
        ),
        migrations.AddField(
            model_name='userhabitdetail',
            name='days_to_achieve',
            field=models.IntegerField(blank=True, default=21, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userhabitdetail',
            name='times_per_day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.CharField(editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='achieved_habit',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='skip_day',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
