# Generated by Django 5.0.7 on 2024-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_remove_habit_days_to_achieve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='times_per_day',
            field=models.IntegerField(default=1),
        ),
    ]
