# Generated by Django 5.0.7 on 2024-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0004_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=213, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
