# Generated by Django 5.0.7 on 2024-07-18 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_remove_user_nickname_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabitdetail',
            name='completed_per_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='days_to_achieve',
            field=models.IntegerField(blank=True, default=21, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='times_per_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
