# Generated by Django 5.0.7 on 2024-07-19 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0007_alter_userhabitdetail_completed_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabitdetail',
            name='completed_per_day',
        ),
        migrations.RemoveField(
            model_name='userhabitdetail',
            name='times_per_day',
        ),
        migrations.AddField(
            model_name='userhabit',
            name='completed_per_day',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userhabit',
            name='times_per_day',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
