# Generated by Django 5.0.7 on 2024-07-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0009_alter_habit_description_alter_habit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhabit',
            name='completed_per_day',
        ),
        migrations.RemoveField(
            model_name='userhabit',
            name='times_per_day',
        ),
    ]
