# Generated by Django 5.0.7 on 2024-07-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0010_remove_userhabit_completed_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='userhabitdetail',
            options={'ordering': ('user_habit__date_of_assign',)},
        ),
        migrations.AlterField(
            model_name='userhabitdetail',
            name='achieved_habit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
