# Generated by Django 5.0.7 on 2024-07-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0011_alter_habit_options_alter_userhabitdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhabitdetail',
            options={'ordering': ('-user_habit__date_of_assign',)},
        ),
    ]
