# Generated by Django 5.0.7 on 2024-07-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0012_alter_userhabitdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('name',), 'verbose_name': 'habit', 'verbose_name_plural': 'habits'},
        ),
        migrations.AlterModelOptions(
            name='userhabitdetail',
            options={'ordering': ('-user_habit__date_of_assign',), 'verbose_name': 'User-Habit Detail', 'verbose_name_plural': 'User-Habit Details'},
        ),
    ]
